# Generated by Django 2.2.5 on 2019-09-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('field', models.CharField(choices=[('AR', 'Architect'), ('CM', 'Commerce'), ('CN', 'Constructor'), ('DE', 'Designer'), ('LS', 'Landscape'), ('MA', 'Marble')], default='MA', max_length=2)),
                ('remarks', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('phone', models.IntegerField()),
                ('pending', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('DO', 'Dolomite'), ('GR', 'Granite'), ('LS', 'Limestone'), ('MA', 'Marble'), ('ON', 'Onyx'), ('SA', 'Sandstone'), ('ST', 'Stone'), ('TR', 'Travertine'), ('QU', 'Quartz')], default='MA', max_length=20)),
                ('colorPrimary', models.CharField(max_length=20)),
                ('colorSecondary', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('reminder', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
