# Generated by Django 2.2.5 on 2019-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='pending',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reminder',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='colorSecondary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='type',
            field=models.CharField(blank=True, choices=[('DO', 'Dolomite'), ('GR', 'Granite'), ('LS', 'Limestone'), ('MA', 'Marble'), ('ON', 'Onyx'), ('SA', 'Sandstone'), ('ST', 'Stone'), ('TR', 'Travertine'), ('QU', 'Quartz')], default='MA', max_length=20),
        ),
    ]
