# Generated by Django 2.2.5 on 2019-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190912_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
